### ISSUE TITLE
 sql过长会被截取 ， 函数名 过长也会进行截取 源数据那边做了截取处理，可否不要截取

### ISSUE THREAD

**Issue by 12gameRensheng** [longxinH/xhprof-apm#14]
如图所示 ： sql过长会被截取 ， 函数名 过长也会进行截取 源数据那边做了截取处理，可否不要截取
![image](https://user-images.githubusercontent.com/45571957/127653285-1eb19cff-cbd0-4925-bde9-7290456bb12e.png)

**Comment by longxinH** [comment]
在xhprof已经做过不限制字符长度的尝试，当出现很长的字符串的时候，会出现内存溢出，导致段错误。[commit](https://github.com/longxinH/xhprof/commit/184c319590c47dea84dd9ac29dfc2e356f52f2ed#diff-bc785865ed7057ef6d4deada7e165031ee7c81494ce34c5d5a4250c4ea11f0e5L1015)

**Comment by longxinH** [comment]
目前是限制512，可以适当的加大限制范围

**Comment by 12gameRensheng** [comment]
大佬你好 因为我不懂c代码 可以弄成一个配置吗 默认就是512 读取apm.ini 或者 php.ini里面的配置进行

**Comment by longxinH** [comment]
提议不错，我这边修改一下

**Comment by 12gameRensheng** [comment]
大佬 你修改代码时 能不能顺便把我提的 那个 每个函数里面也加一个作者 如果有读取处理 
格式就统一按照php的注释规范 
格式如下：* @author liangdabiao 如下图所示
https://github.com/longxinH/xhprof-apm/issues/13

**Comment by 12gameRensheng** [comment]
管理ui界面 我愿意花时间完善下 作者的参数 和进行PR

**Comment by longxinH** [comment]
我看了代码，mysql没有截取的，看一下是不是php输出的时候截取了。

**Comment by 12gameRensheng** [comment]
大佬 我目前测试当函数名超过502 扩展里面会自动截取处理。
例子如下：
 1. 创建一个测试文件 
![image](https://user-images.githubusercontent.com/45571957/128111359-5375329e-9d9e-4a6e-82ff-df071a4ecd00.png)
2. 执行代码 
![image](https://user-images.githubusercontent.com/45571957/128111418-6eb529bb-983d-45f8-a51a-baf9a52b8f10.png)
3.  export.php 处理导入代码中 做下处理 将扩展里面传递的变量 $_apm_export 存储到本地的./年_月_日_时_分_秒.json 文件
![image](https://user-images.githubusercontent.com/45571957/128111523-2be9930a-60a7-4c75-a0b5-cb365255cb66.png)
4.  打开json文件 查看 函数t1的结尾数字对上了  但是函数z1的结尾数字对不上
![image](https://user-images.githubusercontent.com/45571957/128111693-9ad02fa1-8b4a-4eb3-8567-f5d7d0b9ae67.png)
![image](https://user-images.githubusercontent.com/45571957/128111714-e98ab4cd-69e2-470f-9720-be2fdb252a65.png)

**Comment by longxinH** [comment]
最新版本支持设置长度，```apm.scratch_buf = 1024```

**Comment by 12gameRensheng** [comment]
感谢 大佬 我现在试试

**Comment by 12gameRensheng** [comment]
感谢大佬 已经可以了
![image](https://user-images.githubusercontent.com/45571957/128119908-6790c927-92cd-4951-a5b0-e7aea2c0d177.png)

**Comment by longxinH** [comment]
```apm.scratch_buf``` 不建议设置过大
