### ISSUE TITLE
关于apm.ini配置 GET参数 是否开启性能分析的问题

### ISSUE THREAD

**Issue by 12gameRensheng** [longxinH/xhprof-apm#15]
![image](https://user-images.githubusercontent.com/45571957/127794089-9dd148c6-80e6-4406-8074-fafb0ce006ee.png)

大佬 你好 这个在实际应用中发现了一点问题
例如tp  yii  laravel 等 使用模块，路由，控制器的
例如：  我登录方法想做 性能分析 
但是 其他的方法我又不想做性能分析 

此时 我在登录方法 （控制器里面加上代码） :  $_GET['apm_debug'] = ''; 发现没有触发到amp.ini的参数 apm.debug
就是只能通过 url的形式才会触发
![image](https://user-images.githubusercontent.com/45571957/127794413-4ce85c31-a756-4267-b6f2-03687566effd.png)

问下大佬 这个时候要怎么弄成具体通过配置某些控制器 或者 url 就性能分析 某些就不性能分析

**Comment by 12gameRensheng** [comment]
![image](https://user-images.githubusercontent.com/45571957/127794653-9c6cf702-6228-4f49-af1c-2deff6663799.png)

web/index.php

**Comment by longxinH** [comment]
$GET['amp_debug']的解析是在请求开始的时候就开始解析，所以在php层面的设置是没有用的

**Comment by longxinH** [comment]
性能收集的开关在解释请求阶段已经确定好，换句话来说就是，还没解析php文件就确定好了
> 配置某些控制器
2. url的形式比较多，例如/user/login或者index.php?c=user&a=login，前者不需要匹配query，后者需要匹配query
>  通过配置url

如果是特定的路由才触发，推荐使用 [xhprof](https://github.com/longxinH/xhprof)，按照自身的需求去开启。

**Comment by 12gameRensheng** [comment]
感谢大佬  已非常清楚了
