### ISSUE TITLE
编译未通过

### ISSUE THREAD

**Issue by bostin** [longxinH/xhprof-apm#2]
![image](https://user-images.githubusercontent.com/17870778/32141153-bedc5e98-bcb3-11e7-83d2-412b92521aca.png)
请教大神，这个问题可有解决的方法？

在docker环境中，PHP版本：7.1.0，docker里面是ubuntu 16.04的系统

**Comment by longxinH** [comment]
目前只有php5的版本，7的版本还没出

**Comment by bostin** [comment]
哦哦，好的，谢谢
