### ISSUE TITLE
堆栈信息能把文件名和函数所在行号带上吗

### ISSUE THREAD

**Issue by reynaldliu** [longxinH/xhprof-apm#3]
堆栈信息能把文件名和函数所在行号带上吗

**Comment by longxinH** [comment]
@reynaldliu 因为xhprof是把函数的调用次数都统计在一次，如果存在不同地方调用函数，需要把这部分拆开来。昨晚也尝试了一下改动，目前由于工作比较忙，这部分可能稍后才能完成。谢谢你的支持

**Comment by longxinH** [comment]
@reynaldliu 已经完成了支持 https://github.com/longxinH/xhprof-apm/commit/fcbd62e2a7bc99e8e7d8514b36f1d538c16422f5
