### ISSUE TITLE
在PHP7的laravel框架中502

### ISSUE THREAD

**Issue by neatlife** [longxinH/xhprof-apm#6]

**Comment by longxinH** [comment]
问题解决了？还是什么？

**Comment by longxinH** [comment]
@RandomLive 问题解决了？还是？

**Comment by neatlife** [comment]
@longxinH 没有，发现是opcache的原因，关闭opcache后，502消失了，如果配合opcache能用更好，就可以在生产环境上部署了。

**Comment by longxinH** [comment]
@RandomLive 好的。我debug跟追一下，谢谢你的意见。
