### ISSUE TITLE
macos 环境, php7 下的执行时间好像不对, 都特别大

### ISSUE THREAD

**Issue by ppyupp** [longxinH/xhprof-apm#9]
macos 环境, php7 下的执行时间好像不对, 都特别大

mysqli_stmt::execute
43974.228 ms
mysqli::prepare
19886.453 ms
StmtModel::_parseSpecCondition
5118.376 ms
NeatMysqliStmt::Query
3726.674 ms
StmtModel::Get
3168.445 ms
substr
3124.396 ms

这个页面其实不是很慢, 顶多300ms

**Comment by longxinH** [comment]
谢谢，后续会找时间排查。

**Comment by ppyupp** [comment]
很有用的扩展, 多谢了, 我也查查

**Comment by longxinH** [comment]
linux下是否正常

**Comment by longxinH** [comment]
请用最新的master分支
